name: Build APK

on:
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-20.04
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Build APK
      uses: ArtiomTr/buildozer-action@v1
      with:
        command: buildozer android debug
        buildozer_version: stable
        
    - name: Upload APK
      uses: actions/upload-artifact@v3
      with:
        name: luxamine-apk
        path: bin/*.apk
